### PR TITLE
PSE-4955: Upgrade dependencies

### PR DESCRIPTION
**Pull request by cristhian-bento**
This PR upgrades different dependencies to reduce the critical vulnerabilities from 10 to only 2. An important upgrade is Webpack, which was upgraded from v3 to v5, replacing the Extract Text Webpack Plugin (deprecated) and now using Mini CSS Webpack Plugin.

NOTES: 

- I was not able to make it work with Node Hydrogen yet (weird node-gyp error), that's why I created a `.nvmrc` with Fermium version.
- There are still 2 critical vulnerabilities caused by loader-utils, but given the ticket effort I already spent, I think we can add 2 more tickets as tech debt and dep update.
- I was able to make it work locally, that's why there are some assets being added to the dist folder. I was also able to run it in watch mode. QA still pending in staging environment.

### CODE REVIEW

**Review by Dario0117 — APPROVED** [review]

**Comment by wassermandh** [comment]
Great job!! Thank you for doing this, and sorry for the delay in reviewing. Were we able to get this tested on staging?

**Comment by cristhian-bento** [comment]
> Great job!! Thank you for doing this, and sorry for the delay in reviewing. Were we able to get this tested on staging?

thanks! not yet, I was waiting for reviews on this before testing it... but I can do it right now, I will let you know the final result

**Comment by cristhian-bento** [comment]
@wassermandh FYI it is working as expected: https://littlespain.pse-4955upgrade-dependencies.getbento.dev/mercado/. The only thing I noticed is that the CSS styles are a bit different. We may need to ask Pierre about this when he's back, before merging to master. https://www.littlespain.com/mercado/

**Comment by cristhian-bento** [comment]
adding @jguilindro since he also worked on this theme in the past and could potentially have more information on this 😁

**Comment by wassermandh** [comment]
@cristhian-bento When you get the chance, can you list all the critical vulnerabilities that are being removed w/ this PR?

**Comment by cristhian-bento** [comment]
> @cristhian-bento When you get the chance, can you list all the critical vulnerabilities that are being removed w/ this PR?

sure thing!

**Comment by cristhian-bento** [comment]
the only one that is pending: `Prototype pollution in webpack loader-utils`. npm audit shows 2 critical, but it's the same one with a different "path".

here you go! 

image

**Review by wassermandh — APPROVED** [review]

**Pull request merged**
